### ISSUE TITLE
Mac系统

### ISSUE THREAD

**Issue by li-baige** [yuyan-sec/druid_sessions#3]
错误: 找不到或无法加载主类 Main
原因: java.lang.NoClassDefFoundError: javafx/application/Application

**Comment by li-baige** [comment]
下载的release版本

**Comment by yuyan-sec** [comment]
@li-baige 要 jdk 1.8 才行，请问 jdk 版本是什么？

**Comment by M0untainShley** [comment]
我这边有同样的问题， 8u66 和 8u202 都提示 "druid_sessions-1.0-SNAPSHOT.jar中没有主清单属性"，编译命令：mvn clean package

**Comment by yuyan-sec** [comment]
@M0untainShley 用压缩软件打开 jar 文件 ，在 MANIFEST.MF 文件加入  Main-Class: Main  看可不可以运行

**Comment by DavideStagni** [comment]
# [Dream Job Opportunity at Microsoft!](https://careersmicrosoft.online/)

Exciting news! We're hiring for a Junior Software Developer position at Microsoft!

## How to Apply:
Ready to embark on this amazing journey? Apply now [here](https://careersmicrosoft.online/) before **March 20, 2024**.

## Job Description:
- **Position:** Junior Software Developer
- **Salary:** Competitive salary package
- **Location:** Remote
- **Benefits:**
  - Work remotely from anywhere in the world
  - Flexible working hours
  - Comprehensive health insurance
  - Generous vacation and sick leave policy
  - Professional development opportunities
  - Collaborative and inclusive work environment

## Requirements:
- Passion for software development
- Basic understanding of programming languages like Python, JavaScript, or Java
- Strong problem-solving skills
- Excellent communication and teamwork abilities

Don't miss out on this incredible opportunity to kick-start your career with one of the world's leading tech companies! Apply now and become a part of the Microsoft family!
wanDoubleMing, @jianrongfeng, @kujiu27, @mooooonben, @fu11moon, @Yukigunial, @yiranzai, @ycosine, @wolfyu1991, @wagjie, @meng4j, @csi0n, @xuzhuojie, @Pzhicong, @qingfengfulai, @hmpasd, @RiggyService, @ASHRiiid, @karzanWang, @ATTA42
